" inspired by:
"  https://gist.github.com/pthrasher/3933522
"  http://dougblack.io/words/a-good-vimrc.html

" Pathogen for vim plugins in ~/.vim/bundle/ folder
call pathogen#infect()
call pathogen#helptags()

" To disable a plugin, add it's bundle name to the following list
let g:pathogen_disabled = []

syntax on
colorscheme hybrid

set mouse=a

set nocompatible
set updatetime=250

set nowrap
set number
set smartindent
set tabstop=4           " number of visual spaces per TAB
set softtabstop=4       " number of spaces in tab when editing
set expandtab           " tabs are spaces
set shiftround          " tab / shifting moves to closest tabstop.
set autoindent          " Match indents on new lines.
set cursorline          " highlight current line
set showcmd             " show command in bottom bar
filetype indent on      " load filetype-specific indent files
set lazyredraw          " redraw only when we need to.
set showmatch           " highlight matching [{()}]

" don't nag me when hiding buffers
set hidden " allow me to have buffers with unsaved changes.
set autoread " when a file has changed on disk, just load it. Don't ask.

" leader is a key that allows you to have your own "namespace" of keybindings.
" You'll see it a lot below as <leader>
let mapleader = ","

" Quick buffer switching - like cmd-tab'ing
nnoremap <leader><leader> <c-^>

" So we don't have to reach for escape to leave insert mode.
inoremap jk <esc>

" bindings for easy split nav
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" swith between header/source files
nnoremap <C-Up> :e %<.h <cr>
nnoremap <C-Down> :e %<.c <cr>

" build tags with :!ctags -R .
nnoremap <leader>r :pop<cr>
nnoremap <C-t> <C-]>

" Bash like keys for the command line
cnoremap <C-A>      <Home>
cnoremap <C-E>      <End>
cnoremap <C-K>      <C-U>

" Indentation
nnoremap <Tab> >>_
nnoremap <S-Tab> <<_
inoremap <S-Tab> <C-D>
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv

" navigation
nnoremap <C-k> <C-U>
nnoremap <C-j> <C-D>
nnoremap <C-e> $
nnoremap <C-a> ^
inoremap <C-e> <Esc>A
inoremap <C-a> <Esc>I
